
---
- hosts: all
  tasks: 
  - name: grub stage 1
    lineinfile:
      dest: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames)\"[^\"]+)(\".*)'
     #  regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames)\"[^\"]+)
      line: '\1 net.ifnames=0\2'
     # line: '\1 net\.ifnames=0\2'
      backrefs: yes
      state: present
      
  - name: grub stage 2
    lineinfile:
      dest: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* biosdevname)\"[^\"]+)(\".*)'
      line: '\1 biosdevname=0\2'
      backrefs: yes
      state: present

  - name: generate
    command: 
      cmd: grub2-mkconfig
...
