version: '3.3'
services: 
    database:
        container_name: database
        build:
            context: ./db
        ports: 
            - 5432:5432
        volumes:
            - /dbvolume:/var/lib/postgresql/data
        networks:
           - default  
    
    frontendnginxnpm:
        container_name: frontend
        build:
            context: ./frontend
        ports: 
            - 3000:8080
        depends_on: 
            - backenddjango
            - database
        networks:
            - public      
            
            
    backenddjango:
        container_name: backend
        build: 
            context: ./lib_catalog
        depends_on:
            - database
        ports:
            - 8000:8000
        networks:
            - default
        command: /bin/sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
        
networks:
    default:
    public:    
   
